pipeline {
    agent any
    stages {
        stage('List Files') {
            steps {
                sh 'ls -l'
            }
        }
        stage('Build and Test') {
            steps {
                echo "build ..."
            }
        }
    }
}