jenkins:
  systemMessage: "\n\n=== Jenkins Configuration as Code ===\n\n"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${adminpw:-${JENKINS_ADMIN_PASSWORD}}"

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Read:anonymous"
        - "GROUP:Overall/Administer:authenticated"
        - "USER:Overall/Administer:admin"

  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true

  nodes:
    - permanent:
        name: "static-agent"
        remoteFS: "/home/jenkins"
        launcher:
          inbound:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp4"

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope:    GLOBAL
            id:       github-user
            username: ewelina
            password: ${github:-githubPassw0rd}
            description: github username/password

tool:
  git:
    installations:
      - name: Default
        home: "git"

jobs:
  - script: |
      multibranchPipelineJob('configuration-as-code') {
        factory {
          workflowBranchProjectFactory {
            scriptPath('cicd/Jenkinsfile')
          }
        }
        branchSources {
          git {
            id = 'configuration-as-code'
            remote('https://github.com/piotex/EconomicNews.git')
          }
        }
      }

unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true